version: "3.3"
services:
  app:
     build: ./
     command: nodemon -L --inspect /app/index.js
     volumes:
       - ./src:/app/src
     networks:
       - backend
     ports:
       - 3000:3000
     environment:
       NODE_ENV: development
     depends_on:
       - mysql
     env_file:
       - .env
  redis:
    image: redis
    networks:
      - backend
  mysql:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - mysqldbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db
volumes:
    mongodbdata:
    mysqldbdata:
networks:
  backend: